/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package application;

import construction.Aeroport;
import construction.Algos;
import construction.Graphe;
import construction.Intersection;
import construction.Vols;
import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.Dimension;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.util.logging.Level; // Add this import statement
import java.util.logging.Logger; // Add this import statement
import org.graphstream.graph.Graph;
import org.graphstream.ui.swingViewer.View;
import org.graphstream.ui.swingViewer.Viewer;


/**
 *
 * @author Enzo
 */
public class ColorationPanel extends javax.swing.JFrame {
    private Graph currentGraph;
    /**
     * Creates new form ColorationPanel
     */
    public ColorationPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        LabelKmax = new javax.swing.JLabel();
        ComboAlgo = new javax.swing.JComboBox<>();
        BouttonAlgo = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelConflit = new javax.swing.JLabel();
        LabelNewKmax = new javax.swing.JLabel();
        TextNewKmax = new javax.swing.JTextField();
        BouttonNewKmax = new javax.swing.JButton();
        SliderZoom = new javax.swing.JSlider();
        jSeparator2 = new javax.swing.JSeparator();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 264, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 298, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(jPanel3);

        LabelKmax.setText("Kmax :");

        ComboAlgo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gloutonne", "Welsh-Powell", "Largest First Coloring", "Dsatur" }));
        ComboAlgo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboAlgoActionPerformed(evt);
            }
        });

        BouttonAlgo.setText("Lancer l'algo");
        BouttonAlgo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BouttonAlgoActionPerformed(evt);
            }
        });

        jLabelConflit.setText("Conflit : ");

        LabelNewKmax.setText("Nouveau Kmax : ");

        TextNewKmax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextNewKmaxActionPerformed(evt);
            }
        });

        BouttonNewKmax.setText("Mettre à jour");
        BouttonNewKmax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BouttonNewKmaxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ComboAlgo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BouttonAlgo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelNewKmax)
                            .addComponent(LabelKmax, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelConflit)
                            .addComponent(TextNewKmax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BouttonNewKmax, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(SliderZoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator2)
                            .addComponent(jSeparator1))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ComboAlgo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BouttonAlgo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelKmax)
                            .addComponent(jLabelConflit))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelNewKmax)
                            .addComponent(TextNewKmax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(BouttonNewKmax)
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addComponent(SliderZoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ComboAlgoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboAlgoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboAlgoActionPerformed

    private void BouttonAlgoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BouttonAlgoActionPerformed
        String selectedAlgorithm = (String) ComboAlgo.getSelectedItem();
        Graph gcolor;
        
        try {
            File selectedFile = selectFile();
            if (selectedFile != null) {
                if (selectedFile.getName().endsWith(".txt")) {
                    gcolor = Graphe.chargerGraphe(selectedFile.getAbsolutePath());
                } else if (selectedFile.getName().endsWith(".csv")) {
                    List<Vols> vols = loadVols(selectedFile);
                    List<Aeroport> ports = loadAeroports();
                    gcolor = Intersection.setVolsCollision(vols, ports);
                } else {
                    JOptionPane.showMessageDialog(null, "Unsupported file format.");
                    return;
                }

                int chromaticNumber = 0;

                if (selectedAlgorithm != null) {
                    switch (selectedAlgorithm) {
                        case "Gloutonne":
                            chromaticNumber = Algos.Gloutonne(gcolor);
                            break;
                        case "Welsh-Powell":
                            chromaticNumber = Algos.welshPowell(gcolor);
                            break;
                        case "Largest First Coloring":
                            chromaticNumber = Algos.largestFirstColoring(gcolor);
                            break;
                        case "Dsatur":
                            chromaticNumber = Algos.dsatur(gcolor);
                            break;
                        default:
                            JOptionPane.showMessageDialog(null, "Sélection d'algorithme non valide.");
                            break;
                    }
                }

                if (gcolor != null) {
                    currentGraph = gcolor;
                    displayGraph(gcolor, chromaticNumber);
                    jLabelConflit.setText("Conflit : " + chromaticNumber);
                    LabelKmax.setText("Kmax : " + gcolor.getNodeCount());
                }
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_BouttonAlgoActionPerformed

    private void SliderZoomStateChanged(javax.swing.event.ChangeEvent evt) {
        if (currentGraph != null) {
            double zoomFactor = SliderZoom.getValue() / 50.0;
            View view = (View) jPanel3.getComponent(0);
            view.getCamera().setViewPercent(zoomFactor);
        }
    }

    private File selectFile() {
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File("."));
        fileChooser.setFileFilter(new FileNameExtensionFilter("Text and CSV Files", "txt", "csv"));
        int returnValue = fileChooser.showOpenDialog(this);
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            return fileChooser.getSelectedFile();
        }
        return null;
    }

    private List<Vols> loadVols(File csvFile) throws IOException {
        List<Vols> vols = new ArrayList<>();
        try (Scanner scanVol = new Scanner(csvFile)) {
            while (scanVol.hasNextLine()) {
                vols.add(new Vols(scanVol));
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ColorationPanel.class.getName()).log(Level.SEVERE, null, ex);
            throw new IOException("File not found: " + csvFile.getAbsolutePath(), ex);
        }

        return vols;
    }

    private List<Aeroport> loadAeroports() {
        List<Aeroport> ports = new ArrayList<>();
        try (Scanner scanAero = new Scanner(new File("DataTest/aeroports.txt"))) {
            while (scanAero.hasNextLine()) {
                ports.add(new Aeroport(scanAero));
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ColorationPanel.class.getName()).log(Level.SEVERE, null, ex);
            return null;
        }
        return ports;
    }

    private void displayGraph(Graph g, int chromaticNumber) {
        jPanel3.removeAll();

        Viewer viewer = new Viewer(g, Viewer.ThreadingModel.GRAPH_IN_ANOTHER_THREAD);
        viewer.enableAutoLayout();
        viewer.setCloseFramePolicy(Viewer.CloseFramePolicy.CLOSE_VIEWER);

        View view = viewer.addDefaultView(false);
        view.setPreferredSize(new Dimension(500, 500));

        jPanel3.add((Component) view, BorderLayout.CENTER);
        jPanel3.revalidate();
        jPanel3.repaint();
    }

    
    private void TextNewKmaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextNewKmaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextNewKmaxActionPerformed

    private void BouttonNewKmaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BouttonNewKmaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BouttonNewKmaxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BouttonAlgo;
    private javax.swing.JButton BouttonNewKmax;
    private javax.swing.JComboBox<String> ComboAlgo;
    private javax.swing.JLabel LabelKmax;
    private javax.swing.JLabel LabelNewKmax;
    private javax.swing.JSlider SliderZoom;
    private javax.swing.JTextField TextNewKmax;
    private javax.swing.JLabel jLabelConflit;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
